### PR TITLE
add base for helper html creators

### PR DESCRIPTION
**Pull request by oreyes1991**
## HTML Creators
- Div
```js
/* how we used to do it with js */
const main = document.createElement('div')
main.className = 'main-conent';
const wrapper = document.CreateElement('div'); //Let's say I just use this for styling propourse
const child = document.createElement('div');
child.id = 'text';
child.innerText = 'Hello World';
wrapper.appendChild(child);
main.appenChild(wrapper);
/* with helpers */
const main = Div({className: 'main-content'});
const child = main.Div().Div({id: 'text'}, 'Hello world')
```
Both would create the same HTML 
```html
<div class="main-content">
  <div>
    <div id="text">
        Hello wolrd
    </div>
  </div>
</div>
```

### CODE REVIEW

**Comment by oreyes1991** [comment]
- add baseNode function
example
```js
Div().Div().UL().Li().baseNode()
```
this will retrun from the parent instead of the last element
```html
<div>
  <div>
    <ul>
       <li></li>
    </ul>
  </div>
</div>
```
- add content to support callback function
```js
Ul({}, () => (
    [1, 2, 3].map(n => {
       Li({}, n) 
   })
));
```
this will return 
```html
<ul>
   <li>1</li>
   <li>2</li>
   <li>3</li>
</ul>
```
- Add onStoreEvent
this will listen to a single store event, the callback param bring state and the current element
```js
Div().Span().onStoreEvent('my-event', (state, el) => {
      el.innerText = state.Main.text //el would be the span
})

**Comment by oreyes1991** [comment]
- add Table, Tr, Td, Th
Example: 
```js
const header = ['first name', 'last name', 'age']
const rows = [['Jill', 'Smith', '40'], ['Eve', 'Jackson', '39']]
const table = Table({className: 'people'}, () => (
    [
        Tr({}, () => ( header.map(hName => ( Th({}, hName) )) )),
        ...rows.map(row => (
            Tr({}, () => ( row.map(col => ( Td({}, col) ) ) ))
        ))
    ]
))
```
this will generate:
```html
<table class="people">
  <tr>
    <th>first name</th>
    <th>last name</th>
    <th>age</th>
  </tr>
  <tr>
    <td>Jill</td>
    <td>Smith</td>
    <td>40</td>
  </tr>
  <tr>
    <td>Eve</td>
    <td>Jackson</td>
    <td>39</td>
  </tr>
</table>
```

**Comment by oreyes1991** [comment]
- Add Events
```js
Div({}, () => (
  {
    content: Div().Div().H1({}, 'Hello world').baseNode(),
    events: {
        'EVENT_NAME': (action, state) => { /* logic */ },
        'OTHER_EVENT': (action, state) => { /* logic */ }
    }
  }
));
```

- Add more elements
Examples
``` js
Select({}, () => (
     [
        Option({},'option Default'),
        Option({onclick: () => { console.log('option 1') }},'option 1'),
        Option({onclick: () => { console.log('option 2') }},'option 2')
    ]
))
```
```html
<select>
  <option>option Default</option>
  <option>option 1</option>
  <option>option 2</option>
</select>
```
```js
Form({}, () => (
    [
        Label({}, 'Email'),
        Input({type:'email', placeholder:'example@dom'}),
        Label({}, 'Password'),
        Input({type:'password', placeholder:'Password'}),
        Button({id: 'btn-from'}, 'Login')
    ]
));
```
```html
<form>
  <label>Email</label>
  <input type="email" placeholder="example@dom">
  <label>Password</label>
  <input type="password" placeholder="Password">
  <button id="btn-from">Login</button>
</form>
```
```js
A({href: '#metaflux'}, 'Click me');
```
```html
<a href="#metaflux">Click me</a>
```
## Complete List of elements helpers: 
- 'H1',
- 'H2',
- 'H3',
- 'H4',
- 'H5',
- 'H6',
- 'Div',
- 'Span',
- 'Ol',
- 'Ul',
- 'Li',
- 'Table',
- 'Thead',
- 'Tbody',
- 'Tfoot',
- 'Tr',
- 'Td',
- 'Th',
- 'Form',
- 'Label',
- 'Input',
- 'TextArea',
- 'Button',
- 'Img',
- 'Picture',
- 'Source',
- 'Select',
- 'Option',
- 'P',
- 'A',
- 'Section',
- 'Video'

**Comment by oreyes1991** [comment]
# Update
- Remove jsonpath dependency, this leaves to a 9kb metaflux.js file
- util prototype function setAttributes 
```js
const el = document.querySelector('#element');
el.setAttributes({'att-name': 'value', ...})
```

**Comment by jegj** [comment]
i do not remember why we have jsonpath installed ... i think Rein added for some validation

**Review by jegj — APPROVED** [review]

**Review by pablolimo — APPROVED** [review]

**Review by ReinsBrain — APPROVED** [review]
superb

**Pull request merged**
