### PR TITLE
Fix issues in descktop view

### PR DESCRIPTION
**Pull request by oreyes1991**
- Fix socials colors in the header.
- Match button style with the new design.
- add max-width for bigger screens.
- add missing text in home view
- Add more separation in the header.
- Add more line height to the P elements.
- Add MonoSpace font for the code highlight.
- Add missing arrow in the blog section.
- Fix the text in the bottom blog banner.
- Bigger Logo in the home view.
- Smaller logo in the header.
- Fix max-width in the footer.

### CODE REVIEW

**Review by pablolimo — APPROVED** [review]

**Comment by jegj** [comment]
im1
- I think we should increase the font size. On big screens, that is a really tiny font
- There is a big blank space between the icons and the big image of left side, not sure if that is fine
- align the header, it is not in the middle

**Comment by jegj** [comment]
img2
- Fix the alignment of the icons

**Comment by jegj** [comment]
img3
- Too much space for that single section ???

**Comment by jegj** [comment]
blank
- blank section between the footer and the features

**Comment by jegj** [comment]
img1
- Odd behavior of the sidebar
-  Blank section without content

**Comment by jegj** [comment]
img2
- blank space after footer

**Review by jegj — CHANGES_REQUESTED** [review]
- I left notes and screenshots in the PR's comments

**Comment by oreyes1991** [comment]
> * I left notes and screenshots in the PR's comments

I'm going to check those out, please can you give me your resolution?.
this pull request I tested in 1688 px wide.

**Comment by oreyes1991** [comment]
Fixed errors with the UI:
- fix font scaling on big screens.
- fix logos and image scaling on big screens.
- fix white space between the footer and the content in the home view
- fix white space at the end of the footer

@jegj please check it out I testes these changes in 1080, 2k, and 4k with chrome and Firefox

**Review by jegj — APPROVED** [review]
Looks nice !! - if there are not more observations I think this PR is ready for merging

**Pull request merged**
