### PR TITLE
fix inconsistent functions 

### PR DESCRIPTION
**Pull request by oreyes1991**
## Fix onStoreEvent prototype
In the previous version, onStoreEvents will return undefined due is a void function, this will break the chaining behavior.
- update now will return the element that call the onStoreEvents and will have their prototype allowing to keep chaining as usual.
```js
Div().Button().onStoreEvent(...).baseNode()
```
## Create new function ```DefineElement()``` in replace of ```window.customElements.define()```
it receives the same parameters and works the same but also will create a helper function to create your new component like the custom elements (Div, Span ...), the name from that element will be capitalized (my-component = MyComponent), this also will be created to the HTMLElement prototype so can be used with the Metaflux chaining
```js
import { MetaComponent, Div, Button, DefineElement } from '@rebelstack-io/metaflux';

class Counter extends MetaComponent {
	/**
	 * MetaComponent constructor needs storage.
	 */
	constructor () {
		super(global.storage);
	}
	// eslint-disable-next-line class-method-use-this
	render () {
		const content = Div({}, () => (
			Button({
				onclick: () => {
					this.storage.dispatch({type: 'INCREMENT'});
				}
			}, 'Increase')
		))
		this.text = content.Div({}, this.storage.getState().Main.value)
		content.Button({onclick: () => {
			this.storage.dispatch({type: 'DECREMENT'});
		}}, 'Decrese')
		return content;
	}

	/**
	 * Handle Events in an organized way.
	 */
	handleStoreEvents () {
		return {
			'INCREMENT': () => {
				this.text.textContent = this.storage.getState().Main.value;
			},
			'DECREMENT': () => {
				this.text.textContent = this.storage.getState().Main.value;
			}
		};
	}
}
DefineElement('simple-counter', Counter);
// the old way = window.customElements.define('simple-counter', Counter);
```
Now our Element is available in a function ```SimpleCounter(props, content)```
we can define it as so
```js
Div(false, SimpleCounter())
// or use chaining
Div().SimpleCounter()
```

### CODE REVIEW

**Review by jegj — APPROVED** [review]

**Comment by jegj** [comment]
There is an error on the buiild

**Review by jegj — CHANGES_REQUESTED** [review]
there is an error on the build

**Comment by oreyes1991** [comment]
> there is an error on the build

Yes @jegj , I'm still working on that, I'm improving the jest unit testing to have the new V2 features covered

**Comment by oreyes1991** [comment]
## Update Unit testing and coverage
- All unit testing is now Jest.
- Coverage is Istanbul that is built-in with Jest
- the unit testing is separate by the 3 features of Metaflux (Metaviews, Store, CustomElements).

MetafluxCoverage


## Add new Life cycle function.
For the sake of debugging add ```ComponentDidFail``` to the MetaComponent and MetaShadowComponent, it can be overwritten or called.
```js
class MyComponent extends MetaComponent {
    constructor(customValue) {
        if(!customValue) {
            this.ComponentDidFail(new TypeError('customValue is needed on construct'))
        }
    }
    render() {
        ...
    }
    ComponentDidFail(reason) {
       // Handle you errors here
      // If not overwritten by default will throw reason
    }
}
```
This is useful for handling errors from parent classes.

**Review by jegj — APPROVED** [review]

**Review by pablolimo — APPROVED** [review]

**Pull request merged**
